apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::288761726782:role/eksctl-nvvr-eks-addon-iamserviceaccount-kube--Role1-Xkw9iZhAOdlN
