replicaCount: 1

image:
  repository: nvvrsre/notification-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3006

containerPort: 3006

env:
  - name: PORT
    value: "3006"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
