apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: bnZ2cg==                   # Username(echo -n nvvr | base64) (base64 encoded)
  DB_PASSWORD: bnZ2cnVzczEyMw==       # nvvruss123 (base64 encoded)
