apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: dXNoYXNyZWVzdG9yZXM=                          # Username(echo -n ushasreestores | base64) (base64 encoded)
  DB_PASSWORD: dXNoYXNyZWVzdG9yZXMxMjM=       # ushasreestores123 (base64 encoded)
