replicaCount: 1

image:
  repository: nvvrsre/product-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3002

containerPort: 3002

env:
  dbConfigName: db-config
  dbSecretName: db-secret

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
