apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        argocd-sync-force: "16042346762"
    spec:
      containers:
        - name: product-service
          image: nvvrsre/product-service
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "ushasree-db"
            - name: DB_PASSWORD
              value: "ushasree123"
            - name: DB_NAME
              value: "ushasree_product"
            - name: PORT
              value: "3002"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
