apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: {{ .Values.dbConfig.host | quote }}
  DB_NAME: {{ .Values.dbConfig.name | quote }}
  DB_PORT: {{ .Values.dbConfig.port | quote }}
