apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.dbSecret.user | quote }}
  DB_PASSWORD: {{ .Values.dbSecret.password | quote }}
