replicaCount: 1

image:
  repository: nvvrsre/payment-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3005

containerPort: 3005

env:
  dbConfigName: db-config
  dbSecretName: db-secret

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
