replicaCount: 1

image:
  repository: nvvrsre/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

containerPort: 3001

env:
  dbConfigName: db-config   # ConfigMap name for DB envs
  dbSecretName: db-secret   # Secret name for DB secrets

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
