apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        argocd-sync-force: "16084413457"
    spec:
      containers:
        - name: notification-service
          image: nvvrsre/notification-service:v1
          ports:
            - containerPort: 3006
          env:
            - name: PORT
              value: "3006"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
