name: Ushasree CI Pipeline (Matrix for All Backend Services)

on:
  push:
    branches: [ main ]

jobs:
  build-and-lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        service:
          - api-gateway
          - auth-service
          - cart-service
          - catalog-service
          - notification-service
          - order-service
          - payment-service
          - product-service
          - promo-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Run ESLint
        run: |
          cd ${{ matrix.service }}
          npx eslint server.js start.js tests/ || true
     
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run Unit Tests
        run: |
          cd ${{ matrix.service }}
          npm test
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} ${{ matrix.service }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'       # Set to '1' to fail the job on vulnerabilities
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

